### ISSUE TITLE
Fails to build with Python 3.11 and Cython 0.29.32

### ISSUE THREAD

**Issue by penguinpee** [has2k1/scikit-misc#17]
Hi. I'm trying to package scikit-misc as a dependency of [plotnine](https://pypi.org/project/plotnine/) for Fedora.

The build fails with the following error:

```c
  skmisc/loess/src/_loess.c:198:12: fatal error: longintrepr.h: No such file or directory
    198 |   #include "longintrepr.h"
        |            ^~~~~~~~~~~~~~~
  compilation terminated.
  INFO: gcc: skmisc/loess/src/loessc.c
  skmisc/loess/src/loessc.c: In function ‘ehg183a_’:
  skmisc/loess/src/loessc.c:472:19: warning: storing the address of local variable ‘mess’ in ‘error_message’ [-Wdangling-pointer=]
    472 |     error_message = mess;
        |     ~~~~~~~~~~~~~~^~~~~~
  skmisc/loess/src/loessc.c:462:10: note: ‘mess’ declared here
    462 |     char mess[4000], num[20];
        |          ^~~~
  skmisc/loess/src/loessc.c:46:14: note: ‘error_message’ declared here
     46 | extern char *error_message;
        |              ^~~~~~~~~~~~~
  skmisc/loess/src/loessc.c: In function ‘ehg184a_’:
  skmisc/loess/src/loessc.c:487:19: warning: storing the address of local variable ‘mess’ in ‘error_message’ [-Wdangling-pointer=]
    487 |     error_message = mess;
        |     ~~~~~~~~~~~~~~^~~~~~
  skmisc/loess/src/loessc.c:477:10: note: ‘mess’ declared here
    477 |     char mess[4000], num[30];
        |          ^~~~
  skmisc/loess/src/loessc.c:46:14: note: ‘error_message’ declared here
     46 | extern char *error_message;
        |              ^~~~~~~~~~~~~
```

Apparently the header file has been moved in 3.11 according to the [Python docs](https://docs.python.org/3.11/whatsnew/3.11.html?highlight=longintrepr). However, this [change](https://github.com/cython/cython/pull/4428) was implemented in [Cython 0.29.25](https://github.com/cython/cython/blob/master/CHANGES.rst#02925-2021-12-06).

So, I'm out of clues for the moment.

**Comment by has2k1** [comment]
I have been able to install with python-3.11.0rc1, cython-0.29.32, numpy-1.23.3. This is on macos, but I don't think it would be different for linux.

**Comment by penguinpee** [comment]
Thank you for your reply.

I got a few pointers from the Fedora Python community and the issue appears to be caused by the pre-generated `skmisc/loess/src/_loess.c`. For Fedora the [Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_using_cython) require that all files need to be regenerated during build.

Above error message happened before I realized that `_loess.c` was pre-generated. This seems to suggest it was generated with an older Cython version (<0.29.25) incompatible with Python 3.11.

I'm using the distribution tarball from PyPI, by the way. This forced me to deal with `cythonize.dat` and `PKG-INFO` in order to get the C code regenerated. I'm considering switching to the GitHub release archive. That does not include any pre-generated C code it seems, nor does it come with the pre-compiled library.

I'll let you know if I run up against anything else. Otherwise, I'll close this issue as soon as I got the package approved for Fedora.

**Comment by has2k1** [comment]
You are right, generated files should not be in the pypi tarball!

**Comment by penguinpee** [comment]
For my part the issue is solved. I successfully build (and tested :wink:) scikit-misc using the GitHub tarball. Package is now awaiting review. You may want to keep this open with respect to the generated files in the PyPI tarball.

**Comment by sorenwacker** [comment]
I am trying to install it with pip into a python 3.11 environment with this error:
```

      INFO: building 'floess' library
      error: library floess has Fortran sources but no Fortran compiler found
      INFO:
      ########### CLIB COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : gcc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : -msse -msse2 -msse3
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> /tmp/pip-install-rk0sgvba/scikit-misc_55f8a7108d4d4c6b9d2acb67b727e5c8/build/temp.linux-x86_64-cpython-311/ccompiler_opt_cache_clib.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> scikit-misc
```


after installing a fortran compiler I got:
```

      INFO: building 'skmisc.loess._loess' extension
      INFO: compiling C sources
      INFO: C compiler: gcc -pthread -B /home/swacker/miniconda3/envs/chem/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/swacker/miniconda3/envs/chem/include -fPIC -O2 -isystem /home/swacker/miniconda3/envs/chem/include -fPIC

      INFO: compile options: '-DNO_ATLAS_INFO=1 -DHAVE_CBLAS -I/home/swacker/miniconda3/envs/chem/include -I/home/swacker/miniconda3/envs/chem/lib/python3.11/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.11/numpy/distutils/include -I/home/swacker/miniconda3/envs/chem/include/python3.11 -c'
      extra options: '-msse -msse2 -msse3'
      INFO: gcc: skmisc/loess/src/_loess.c
      INFO: gcc: skmisc/loess/src/loess.c
      INFO: gcc: skmisc/loess/src/loessc.cINFO: gcc: skmisc/loess/src/misc.c
      INFO: gcc: skmisc/loess/src/predict.c

      skmisc/loess/src/_loess.c:198:12: fatal error: longintrepr.h: No such file or directory
        198 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: Command "gcc -pthread -B /home/swacker/miniconda3/envs/chem/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/swacker/miniconda3/envs/chem/include -fPIC -O2 -isystem /home/swacker/miniconda3/envs/chem/include -fPIC -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -I/home/swacker/miniconda3/envs/chem/include -I/home/swacker/miniconda3/envs/chem/lib/python3.11/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.11/numpy/distutils/include -I/home/swacker/miniconda3/envs/chem/include/python3.11 -c skmisc/loess/src/_loess.c -o build/temp.linux-x86_64-cpython-311/skmisc/loess/src/_loess.o -MMD -MF build/temp.linux-x86_64-cpython-311/skmisc/loess/src/_loess.o.d -msse -msse2 -msse3" failed with exit status 1
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
```

**Comment by has2k1** [comment]
Closing since the way the package is built has changed.
